# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy Admin to Test.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodule
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Set up JDK 1.15
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15

      ## Start Tests
      #      - name: Run the Maven verify phase
      #        run: mvn -B verify
      ## End Tests

      # Start Build
      - name: Build All project with Maven
        run: mvn clean install package --file pom.xml -P production
      # End build

      # Start Upload
      - name: Upload an Admin App Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: admin
          # A file, directory or wildcard pattern that describes what to upload
          path: admin/target/admin*

      #  Start Clean Deploy Dir
      - name: Clean Admin Deploy Dir
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.PROJECTX_TEST_01_REMOTE_HOST }}
          username: ${{ secrets.PROJECTX_DEV_01_REMOTE_USER_GOL }}
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PROJECTX_DEV_03_RUNNER_KEY }}

          command: |
            rm -r /home/s.golitsyn_pro/cicd/admin/*

      # End Clean Deploy Dir


      # Start Deploy On Server
      - name: Deploy to Server Admin
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROJECTX_DEV_03_RUNNER_KEY }}
          SOURCE: "admin/target/*exec.jar"
          REMOTE_HOST: ${{ secrets.PROJECTX_TEST_01_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.PROJECTX_DEV_01_REMOTE_USER_GOL }}
          TARGET: /home/s.golitsyn_pro/cicd/admin

      # End Deploy On Server

      #  Restart Entry Point Service
      - name: Restart Admin Service
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.PROJECTX_TEST_01_REMOTE_HOST }}
          username: ${{ secrets.PROJECTX_DEV_01_REMOTE_USER_GOL }}
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PROJECTX_DEV_03_RUNNER_KEY }}

          command: |
            /etc/init.d/admin-console stop
            cp /home/s.golitsyn_pro/cicd/admin/*exec.jar /home/s.golitsyn_pro/admin/admin-console.jar
            /etc/init.d/admin-console start

#  Restart services
