server:
  port: 8081
spring:
  application:
    name: grpc-client
  boot:
    admin:
      client:
        url: http://localhost:8080
# Enable logging
logging:
  level:
    root: INFO
    com.deft: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
