# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.15
      uses: actions/setup-java@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: 1.15

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: otus-algo
        path: |
          build/libs/petproject*
          !dist/**/*.md

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: build/test-results/test/TEST-com.deft.petproject.PetprojectApplicationTests.xml

#  build_and_test:
#
#    runs-on: self-hosted
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          java-version: [ 1.14, 1.8 ]
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: otus-algo
#          path: |
#            build/libs/otus-algo*
#            !dist/**/*.md
#
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v2
#        with:
#          name: code-coverage-report
#          path: output/test/code-coverage.html
